import { useState, useEffect } from 'react';
import { createClient } from '@supabase/supabase-js';
import { supabase } from '../../lib/supabase';
import { getSupabaseEnv } from '../../lib/env';

export default function ManageFaculty() {
  const [faculties, setFaculties] = useState([]);
  const [branches, setBranches] = useState([]);
  const [formData, setFormData] = useState({ fullName: '', email: '', phone: '', password: '', branchId: '' });
  const [toast, setToast] = useState(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

 const fetchBranches = async () => {
    try {
      const { data, error } = await supabase.from('branches').select('*');
      
      if (error) {
        alert("🚨 SUPABASE ERROR: " + error.message);
        console.error("Supabase Error Details:", error);
        setBranches([]);
      } else if (data && data.length > 0) {
        setBranches(data);
      } else {
        alert("⚠️ SUPABASE CONNECTION SUCCESS, BUT TABLE IS EMPTY (0 rows returned).");
        setBranches([]);
      }
    } catch (err) {
      alert("🚨 CODE ERROR: " + err.message);
    }
  };

  const fetchFaculties = () => {
    supabase
      .from('user_profiles')
      .select('*, branches(name)')
      .eq('role', 'faculty')
      .then(({ data, error }) => {
        if (!error && data) setFaculties(data);
      });
  };

  useEffect(() => {
    fetchBranches();
    fetchFaculties();
  }, []);

  const handleAddFaculty = async (e) => {
    e.preventDefault();
    setIsSubmitting(true);

    if (!formData.branchId) {
      setToast({ message: 'Error: Please select a Department/Branch before creating an account.', type: 'error' });
      setIsSubmitting(false);
      return;
    }

    try {
      // Create isolated client to avoid logging out the admin
      const { url, publishableKey } = getSupabaseEnv();
      const tempClient = createClient(url, publishableKey, { auth: { persistSession: false } });

      // Step 1: Create the user in Supabase Authentication officially
      const { data: authData, error: authError } = await tempClient.auth.signUp({
        email: formData.email,
        password: formData.password,
      });

      if (authError) throw authError;

      // Get the real, authenticated UUID generated by Supabase
      const realUserId = authData.user.id;

      // Step 2: Insert into user_profiles using the REAL Auth UUID
      const { error: profileError } = await supabase.from('user_profiles').insert([{
        id: realUserId,
        full_name: formData.fullName,
        phone: formData.phone,
        role: 'faculty',
        branch_id: formData.branchId || null,
        college_id: '11111111-0000-0000-0000-000000000001',
        is_active: true
      }]);

      if (profileError) throw profileError;

      setToast({ message: 'Faculty Added Successfully!', type: 'success' });
      setTimeout(() => {
        setFormData({ fullName: '', email: '', phone: '', password: '', branchId: '' });
        fetchFaculties();
        setIsSubmitting(false);
      }, 100);

    } catch (error) {
      setToast({ message: 'Error: ' + error.message, type: 'error' });
      setIsSubmitting(false);
    }

    setTimeout(() => setToast(null), 4000);
  };

  const handleDeleteFaculty = async (facultyId) => {
    if (window.confirm("Are you sure you want to delete this faculty? This action cannot be undone.")) {
      const { error } = await supabase.from('user_profiles').delete().eq('id', facultyId);

      if (error) {
        alert('Error deleting faculty: ' + error.message);
        return;
      }

      setFaculties(prev => prev.filter(f => f.id !== facultyId));
      alert("Faculty deleted successfully!");
    }
  };

  return (
    <div style={containerStyle}>
      <h2 style={headingStyle}>Manage Faculty 👨‍🏫</h2>

      {toast && (
        <div style={{ ...toastStyle, background: toast.type === 'success' ? '#22c55e' : '#ef4444' }}>
          {toast.message}
        </div>
      )}

      <div style={formContainerStyle}>
        <form onSubmit={handleAddFaculty} style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>

          <div style={{ display: 'flex', gap: '16px', flexWrap: 'wrap' }}>
            <input
              type="text"
              placeholder="Full Name"
              required
              value={formData.fullName}
              onChange={(e) => setFormData({...formData, fullName: e.target.value})}
              style={inputStyle}
            />
            <input
              type="email"
              placeholder="Email Address"
              required
              value={formData.email}
              onChange={(e) => setFormData({...formData, email: e.target.value})}
              style={inputStyle}
            />
          </div>

          <div style={{ display: 'flex', gap: '16px', flexWrap: 'wrap' }}>
            <input
              type="text"
              placeholder="Phone Number"
              value={formData.phone}
              onChange={(e) => setFormData({...formData, phone: e.target.value})}
              style={inputStyle}
            />
            <input
              type="password"
              placeholder="Password"
              required
              value={formData.password}
              onChange={(e) => setFormData({...formData, password: e.target.value})}
              style={inputStyle}
            />
          </div>

          <select
            required
            value={formData.branchId || ""}
            onChange={(e) => setFormData({...formData, branchId: e.target.value})}
            style={selectStyle}
          >
            <option value="" disabled style={{ background: '#1a1a26', color: '#e0e0e0', padding: '10px' }}>-- Select Department / Branch --</option>
            
            {branches && branches.length > 0 ? (
              branches.map(branch => (
                <option key={branch.id} value={branch.id} style={{ background: '#1a1a26', color: '#e0e0e0', padding: '10px' }}>
                  {branch.name}
                </option>
              ))
            ) : (
              <option value="" disabled style={{ background: '#1a1a26', color: '#e0e0e0', padding: '10px' }}>⚠️ No Branches Found in Database</option>
            )}
          </select>

          <button type="submit" style={submitButtonStyle} disabled={isSubmitting}>
            {isSubmitting ? 'Adding...' : '✨ Add Faculty'}
          </button>
        </form>
      </div>

      <div style={tableContainerStyle}>
        <table style={tableStyle}>
          <thead>
            <tr style={tableHeaderRowStyle}>
              <th style={tableHeaderStyle}>Name</th>
              <th style={tableHeaderStyle}>Email</th>
              <th style={tableHeaderStyle}>Phone</th>
              <th style={tableHeaderStyle}>Actions</th>
            </tr>
          </thead>
          <tbody>
            {faculties.map(faculty => (
              <tr key={faculty.id} style={tableRowStyle}>
                <td style={tableCellStyle}>{faculty.full_name}</td>
                {/* Note: if the email column doesn't exist, this will just be blank */}
                <td style={tableCellStyle}>{faculty.email || 'N/A'}</td>
                <td style={tableCellStyle}>{faculty.phone || 'N/A'}</td>
                <td style={tableCellStyle}>
                  <button onClick={() => handleDeleteFaculty(faculty.id)} style={deleteButtonStyle}>
                    🗑️ Remove
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

const containerStyle = { padding: '30px', minHeight: '100vh', background: '#0d0d14', color: '#e0e0e0', fontFamily: "'Inter', sans-serif" };
const headingStyle = { fontSize: '26px', fontWeight: '700', marginBottom: '25px', color: '#ffffff', letterSpacing: '-0.5px' };
const toastStyle = { padding: '14px 20px', borderRadius: '10px', fontWeight: '600', marginBottom: '20px', boxShadow: '0 8px 24px rgba(0,0,0,0.2)', color: '#fff' };
const formContainerStyle = { background: 'rgba(26, 26, 38, 0.6)', backdropFilter: 'blur(12px)', WebkitBackdropFilter: 'blur(12px)', padding: '28px', borderRadius: '16px', marginBottom: '30px', border: '1px solid rgba(255, 255, 255, 0.06)', boxShadow: '0 12px 32px rgba(0, 0, 0, 0.4)' };
const inputStyle = { flex: 1, minWidth: '240px', padding: '13px 16px', borderRadius: '10px', border: '1px solid rgba(255, 255, 255, 0.08)', background: 'rgba(45, 45, 61, 0.5)', color: '#fff', fontSize: '14px', outline: 'none', transition: 'all 0.2s ease', boxSizing: 'border-box' };
const selectStyle = { ...inputStyle, width: '100%', cursor: 'pointer' };
const submitButtonStyle = { padding: '13px 28px', background: 'linear-gradient(135deg, #8b5cf6, #6d28d9)', color: '#fff', border: 'none', borderRadius: '10px', cursor: 'pointer', fontSize: '15px', fontWeight: '600', width: 'fit-content', boxShadow: '0 4px 14px rgba(139, 92, 246, 0.3)' };
const tableContainerStyle = { ...formContainerStyle, padding: '24px', overflowX: 'auto' };
const tableStyle = { width: '100%', textAlign: 'left', borderCollapse: 'collapse', fontSize: '14px' };
const tableHeaderRowStyle = { borderBottom: '2px solid rgba(255, 255, 255, 0.08)' };
const tableHeaderStyle = { padding: '12px 16px', color: '#a0a0b0', fontWeight: '600', textTransform: 'uppercase', fontSize: '12px', letterSpacing: '0.5px' };
const tableRowStyle = { borderBottom: '1px solid rgba(255, 255, 255, 0.04)' };
const tableCellStyle = { padding: '14px 16px', color: '#e0e0e0' };
const deleteButtonStyle = { padding: '6px 14px', background: 'rgba(239, 68, 68, 0.15)', color: '#ef4444', border: '1px solid rgba(239, 68, 68, 0.3)', borderRadius: '8px', cursor: 'pointer', fontSize: '13px', fontWeight: '500' };